export type ConditionCostEstimateActionType =
  | "FETCH_CONDITION_COST_ESTIMATE_START"
  | "FETCH_CONDITION_COST_ESTIMATE_SUCCESS"
  | "FETCH_CONDITION_COST_ESTIMATE_ERROR";

export type ConditionsActionType =
  | "FETCH_CONDITIONS_START"
  | "FETCH_CONDITIONS_SUCCESS"
  | "FETCH_CONDITIONS_ERROR";

export type InsurancesActionType =
  | "FETCH_INSURANCES_START"
  | "FETCH_INSURANCES_SUCCESS"
  | "FETCH_INSURANCES_ERROR";

export type LanguagesActionType =
  | "FETCH_LANGUAGES_START"
  | "FETCH_LANGUAGES_SUCCESS"
  | "FETCH_LANGUAGES_ERROR";

export type LocationsActionType =
  | "FETCH_LOCATIONS_START"
  | "FETCH_LOCATIONS_SUCCESS"
  | "FETCH_LOCATIONS_ERROR";

export type ProvidersActionType =
  | "FETCH_PROVIDERS_START"
  | "FETCH_PROVIDERS_SUCCESS"
  | "FETCH_PROVIDERS_ERROR";

export type SpecialtiesActionType =
  | "FETCH_SPECIALTIES_START"
  | "FETCH_SPECIALTIES_SUCCESS"
  | "FETCH_SPECIALTIES_ERROR";

export type TreatmentsActionType =
  | "FETCH_TREATMENTS_START"
  | "FETCH_TREATMENTS_SUCCESS"
  | "FETCH_TREATMENTS_ERROR";
